Feature/#298 show active subtechniques
mitre-attack/attack-navigator pull request #310
Opened 2021-06-23 19:30 UTC by iguannalin

Feature add for #298; to show active subtechniques even if parent technique is inactive

2021-06-23 19:34 UTC, isaisabel commented
@iguannalin this should target the `develop` branch, not `master`. It looks like it can't currently be retargetted to that branch since it has no commits that aren't on develop yet.

2021-06-23 20:30 UTC, iguannalin commented
> @iguannalin this should target the `develop` branch, not `master`. It looks like it can't currently be retargetted to that branch since it has no commits that aren't on develop yet.

Not sure why that happened, since I branched it off develop in my local machine :/ but I changed the base branch back to develop now.

2021-06-24 13:21 UTC, isaisabel requested changes
Works great! Needs an entry in the changelog though.

2021-06-24 15:17 UTC, isaisabel approved these changes

2021-06-24 15:17 UTC, merged